### ISSUE TITLE
Unable to create a Tracker

### ISSUE THREAD

**Issue by anotinelg** [aws/sagemaker-experiments#113]
**Describe the bug**
In a jupyter notebook, i am not able to create a tracker ! I am not sure if it is really a bug, or a misconception from my part.

**To Reproduce**

in a jupyter notebook:
```
with tracker.Tracker.create(display_name=f"test-tracker",
                    ) as trial_tracker:
        trial_tracker.log_parameter('test', 0.01)
```

this fails to:
```
ClientError: An error occurred (ValidationException) when calling the CreateTrialComponent operation: Trial Component creation is currently restricted to the SageMaker runtime. Try supplying an experiment config when creating a job instead.

```
**Expected behavior**
If i understand the (examples)[https://github.com/shashankprasanna/sagemaker-experiments-examples/blob/master/sagemaker-experiment-examples.ipynb], this code should not give any problem:

**Screenshots**

**Environment:**
jupyter notebook
version of:
 sagemaker_experiments= '0.1.25'
sagemaker =2.19.0

**Additional context**

**Comment by matkalinowski** [comment]
Are there any news on this or possible solutions? I am having the same issue when trying to run sagemaker pytorch estimator with instance_type = 'local'.

**Comment by wangweixun** [comment]
Hi there, sorry for the late response. Can I ask where are you running the code from? The Python SDK code above calls CreateTrialComponent API which is restricted to SageMaker environments only: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrialComponent.html.

**Comment by anotinelg** [comment]
> Hi there, sorry for the late response. Can I ask where are you running the code from? The Python SDK code above calls CreateTrialComponent API which is restricted to SageMaker environments only: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrialComponent.html.

In my case, i was trying to do that in a jupyter sagemaker notebook.

**Comment by danabens** [comment]
Hi Antoine, you should use `Tracker.load` instead of `Tracker.create` in this case. The `load` method is the most common way to instantiate the tracker.

```python
tf_estimator.fit(...job_name = job_name...)

tracker = Tracker.load(training_job_name=job_name, ...)
tracker.log_parameters(hyperparams)
```

**Comment by matkalinowski** [comment]
@wangweixun Thank you for the resposne. So it is not possible to run those experiments locally and log the results to the AWS experiments? (even from the supported docker image?)

**Comment by danabens** [comment]
> is not possible to run those experiments locally and log the results to the AWS experiments? (even from the supported docker image?)

It is not possible.  In order for metrics to show up in Studio/Experiments `log_metric` must be called from a training job instance.
