### ISSUE TITLE
Tracking Non SageMaker Workload

### ISSUE THREAD

**Issue by yapnel** [aws/sagemaker-experiments#142]
Is it possible to use this SDK to track experiments that are not done in SageMaker? Basically, I am performing experiments in pure python on EC2 and I want to use this SDK to track the experiments. If possible, are there examples please?

Thanks

**Comment by alar0330** [comment]
Yes, it is possible. As of today, the SM Experiments API has been opened for all tracking options but _log_metrics_.

**Comment by lorenzwalthert** [comment]
Cool. How is this documented? Where can I learn about these things? I tried https://aws.amazon.com/blogs/aws/category/artificial-intelligence/sagemaker/ or watching this GitHub repo for releases (but there were none recently).

**Comment by yapnel** [comment]
Hi - could somebody please point me to the documentation where I can achieve this? @danabens

**Comment by lorenzwalthert** [comment]
I’d start here. https://aws.amazon.com/blogs/machine-learning/next-generation-amazon-sagemaker-experiments-organize-track-and-compare-your-machine-learning-trainings-at-scale/

**Comment by yapnel** [comment]
Thanks @lorenzwalthert

Just to confirm my understand from the blog, I am able to use the SDK to call the Run class to log any experiments i'm executing locally on my laptop via an IDE. Is that correct?
