### ISSUE TITLE
These 2 statements seem confusing, could you expain in more detail

### ISSUE THREAD

**Issue by rsgrewal-aws** [aws/sagemaker-experiments#157]
**Describe the bug**
The caveat statements are un clear

**To Reproduce**
Associations cannot be created between two experiment entities. For example between an Experiment and Trial.
Associations can only be created between the following resources: Experiment, Trial, Trial Component, Action, Artifact, or Context.

So can we or can we not create association between Experiment and Trial ?

rupinder

**Comment by danabens** [comment]
Hi Rupinder, thanks for identifying this inconsistency. The first statement is correct. Specifically, calling the `AddAssociation` API with both source and destination in the set [Experiment|Trial|TrialComponent] is invalid.
