### ISSUE TITLE
General availability for `log_metric()` in processing jobs and beyond

### ISSUE THREAD

**Issue by lorenzwalthert** [aws/sagemaker-experiments#160]
**Is your feature request related to a problem? Please describe.**
Yes. Coming from MLflow, I can [log metrics from anywhere](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_metric). It works locally, in a training job, in a processing job, on a spark cluster etc. I want to use sagemaker experiments to track not just the training of a model, but also the pre- and post-processing of the features, in particular during sagemaker processing jobs. Examples:
* Know how many observations I dropped during the pre-processing.
* After batch-transform inference, I my want to log some custom metrics back to Sagemaker Experiments, e.g. the precision of the model on the new data.

Original issue: https://github.com/aws/sagemaker-experiments/issues/151#issuecomment-1114991598

**Describe the solution you'd like**

I'd like to be able to call `tracker.log_metric()` from a processing run, ideally even from anywhere (also locally while debugging).
```python
# some omitted import statements
with Tracker.create(display_name="evaluation", sagemaker_boto_client=sm) as tracker:
        tracker.log_metric(metric_name="..." value='my-value', timestamp = datetime.datetime.now())
```

**Describe alternatives you've considered**

Building my own metadata store in S3, which creates friction between my custom solution and Sagemaker Experiments.

**Additional context**

**Comment by Bustami** [comment]
Hi @lorenzwalthert
It would be great to have this issue already solved. I was looking for something similar, specially for custom metrics recording on test dataset or new data performance stuff. 
Anyway, for the moment I got this by using the function  ` log_parameters()` and it worked properly.
Did you try with that?

**Comment by lorenzwalthert** [comment]
Are you suggesting to log metrics as parameters? Sounds like a hack to me. 🙃

**Comment by Bustami** [comment]
haha ok, at least meanwhile.
Anyway, with that approach you are able to set what parameters are shown when comparing trials or their components (is it the goal, is not?.

![image](https://user-images.githubusercontent.com/9221734/174458810-08d6f84e-5ffd-49ab-9b6f-972b5436c964.png)

**Comment by ycrouin** [comment]
We can now send metrics using an API :clap: 
- https://awsapichanges.info/archive/changes/187f23-metrics.sagemaker.html
- https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_Operations_Amazon_SageMaker_Metrics_Service.html

It would be nice to have it integrated with the Tracker object from the sagemaker-experiments package

**Comment by kirit93** [comment]
@lorenzwalthert - you can log metrics from anywhere using the SageMaker Python SDK - https://sagemaker.readthedocs.io/en/stable/experiments/sagemaker.experiments.html#run.

**Comment by lorenzwalthert** [comment]
Yesm I saw that, thanks. Is this repo still under development or are you planning to archieve it?
