### ISSUE TITLE
Log metrics in any environment

### ISSUE THREAD

**Issue by andrew-ge-wu** [aws/sagemaker-experiments#60]
**Is your feature request related to a problem? Please describe.**
I create a Tracker via Tracker.create but I can not use such tracker to log metric.
It throws this log instead.
"Cannot write metrics in this environment."

**Describe the solution you'd like**
The tracker can be created should able to log metrics as well.

**Describe alternatives you've considered**
N/A

**Additional context**
I noticed that the create method creating Tracker with no metrics_writer which required to log metric and there is no way to opt that in. I can not find the intended way to use log_metric API from documentation either, maybe I missed something?

**Comment by danabens** [comment]
Hi Andrew, thanks for creating this issue. We are discussing and will respond shortly.

**Comment by andrew-ge-wu** [comment]
Thanks @danabens, let me know if there's any update.

**Comment by danabens** [comment]
released

**Comment by mooreniemi** [comment]
I'm on sagemaker-experiments 0.1.45 but see:

```
WARNING:root:Cannot write metrics in this environment.
```

**Comment by santoshmedisetty321** [comment]
@danabens I also see the issue on sagemaker-experiments 0.1.45. @mooreniemi Any solution?

**Comment by joslinm** [comment]
I am seeing this as well
