### ISSUE TITLE
Force option on delete()s

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-experiments#74]
**Is your feature request related to a problem? Please describe.**

I see the rationale for making `Experiment.delete()` and `Trial.delete()` functions reject by default if associated Trials/TrialComponents exist... They're potentially destructive operations and accidental data loss should be avoided where possible.

...But honestly, the reason I'm trying to call these functions is because I **want** to delete all the nested objects. Having to loop through all the associations is tedious.

**Describe the solution you'd like**

Offer optional arguments e.g. `delete_trials_and_components: bool=False` by which users can specify that they really do want to delete associated Trial Components on `Trial.delete()`, and both Trials and Trial Components on `Experiment.delete()`.

The sagemaker-experiments SDK should then handle discovering and deleted the associated objects so the user doesn't have to.

**Describe alternatives you've considered**

* De-associating trial components (and also trials, if that's possible?) on parent delete
* Breaking API change to change default behaviour of `.delete()`

**Additional context**

None

**Comment by danabens** [comment]
Hi thanks for creating the issue. We are working on addressing the unexpected delete behavior. In the meantime see the ```cleanup``` method in this example notebook: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-experiments/mnist-handwritten-digits-classification-experiment.ipynb

**Comment by danabens** [comment]
This behavior has been added on the experiment here: [experiment.delete_all()](https://github.com/aws/sagemaker-experiments/blob/master/src/smexperiments/experiment.py#L232)

**Comment by danabens** [comment]
added to trial https://github.com/aws/sagemaker-experiments/pull/98
