### ISSUE TITLE
Broken example notebooks

### ISSUE THREAD

**Issue by rahul003** [aws/sagemaker-experiments#96]
**Describe the bug**
I'm crossposting the issue I created on sagemaker-examples repository as I'm not sure which one is being tracked. Please feel free to close one of them. 

https://github.com/awslabs/amazon-sagemaker-examples/issues/1418

- The framework mode xgboost example does not show any trial components on the studio
- Pytorch mnist example script is broken (multiple issues with logger, data reading, etc). Even without Studio the script wouldn't work I think. 

**To Reproduce**

- Run the notebook as is

**Expected behavior**
- Expect to see trial components and some metrics in it

**Screenshots**
NA

**Environment:**
Default containers and environments. I used the datascience py3 env to launch the job.

Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans): 
Framework Version:
Python Version:
CPU or GPU:
Python SDK Version: 1.50.17
Are you using a custom image: No

**Comment by danabens** [comment]
see https://github.com/awslabs/amazon-sagemaker-examples/issues/1418
